version: '2'

services:
    mail:
        image: tvial/docker-mailserver:latest
        #hostname: host ( HOST.dominio.tld )
        hostname: mail
        domainname: example.com 
        container_name: mail
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - ./maildata:/var/mail # mailbox data
            - ./config/:/tmp/docker-mailserver/ # mailbox configurations
            - /etc/letsencrypt:/etc/letsencrypt # letsencrypt certificates
        environment:
            - SSL_TYPE=letsencrypt # type of ssl certificate
            - ENABLE_FAIL2BAN=1 # block any IP that fail the password 3 times
        cap_add:
            - NET_ADMIN # Fail2Ban requirement

volumes:
    maildata:
        driver: local
